### ISSUE TITLE
docker doesn't install when snap list doesn't reveal docker

### ISSUE THREAD

**Issue by AndrewIammatteo** [BitcoinCacheMachine/BitcoinCacheMachine#27]
When docker was manually uninstalled the following did not install docker. When square brackets were added docker installed but a different error persisted. Will need to make this suitable for all conditions.

```
if ! snap list | grep -q docker; then
    if ! docker image list --format "{{.Repository}},{{.Tag}}" | grep -q "bcm-trezor,$BCM_VERSION"; then
        bash -c "$BCM_GIT_DIR/controller/build.sh"
    fi
else
    bash -c "$BCM_GIT_DIR/cli/commands/install/snap_install_docker.sh"
fi
```

**Comment by farscapian** [comment]
Andrew, I've had this issue on my end as well.  I'm not sure why this doesn't work and I've tried several versions of the command (e.g., single and double square brackets). I couldn't easily find something online either.  There could be a number of reasons for this; I've seen other commands that, for some reason, just don't lend themselves well to automated shell scripts.  Perhaps because they're interactive or are emitting error codes or some such thing. 

I had the same issue with the snap installer for LXD. I'll try to find a solution on my end but this one has been dogging me a while.

**Comment by farscapian** [comment]
I found this article: https://stackoverflow.com/questions/592620/how-to-check-if-a-program-exists-from-a-bash-script/677212#677212

**Comment by farscapian** [comment]
Closing since this section has been refactored.
